require("vim._core.ui2").enable({})

require("binds")
require("pack")
require("options")
require("commands")

require('nord').set()
require('plugins.lualine')
require('plugins.mini')
require('plugins.ibl')
require('plugins.autopairs')
require('plugins.cord')
require('plugins.peek')
require('plugins.highlight')
