set -g status-position bottom
set -g default-terminal "screen-256color"

# prefix
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# settings
set -g mouse on
set -g base-index 1
set -g escape-time 0
set -g renumber-windows on

set-option -g status-keys vi
set-window-option -g mode-keys vi
bind r source-file ~/.config/tmux/tmux.conf \; display " Reloaded!"

bind -r ^ last-window
bind -r k select-pane -U
bind -r j select-pane -D
bind -r h select-pane -L
bind -r l select-pane -R
bind y setw synchronize-panes
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind \" split-window -v -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

# base status bar style
set -g status-style bg="#3B4252",fg="#d8dee9"

# left side of status bar
set -g status-left-length 40
set -g status-left "#[bg=#B48EAD,fg=#2E3440,bold] #S #[bg=default,fg=default] "

# right side of status bar
set -g status-right-length 150
set -g status-right "#[bg=#434c5e,fg=#a3be8c,bold] #{b:pane_current_path} #[fg=#4C566A]| #[fg=#EBCB8B,bold]%d-%m-%Y "

# window status format
set -g window-status-style bg="#434c5e",fg="#d8dee9"
set -g window-status-format " #I:#W "

# active window format
set -g window-status-current-style bg="#BF616A",fg="#2E3440",bold
set -g window-status-current-format " #I:#W "

# pane border colors 
set -g pane-border-style fg="#4C566A"
set -g pane-active-border-style fg="#bf616a"

# message styling
set -g message-style bg="#3B4252",fg="#D08770",bold

# prefix + control s to save the tmux session
# prefix + control r to reload the sesion from tmux resurrect
# prefix + I to install all plugins
