#! /bin/sh

sxhkd &
dunst &
# polybar
~/.config/polybar/launch.sh &

# composting and wallpaper
picom &
feh --bg-fill ~/Pictures/wallpapers/wallpaper20.png
/usr/lib/polkit-kde-authentication-agent-1 &

# wi-fi
nm-applet &

redshift -P -O 4500
brightnessctl set 65

bspc monitor -d I II III IV V VI VII

bspc config border_width         3
bspc config window_gap          7

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config focus_follows_pointer	true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# border colors
bspc config focused_border_color "#4C566A"
bspc config normal_border_color "#3B4252"
