#! /bin/sh

sxhkd &
dunst &
# polybar
~/.config/polybar/launch.sh &

# composting and wallpaper
picom &
feh --bg-fill /home/rv/Downloads/wallpaper3.jpg


redshift -P -O 4500
brightnessctl set 75

bspc monitor -d I II III IV V

bspc config border_width         0
bspc config window_gap          7

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# border colors
# bspc config focused_border_color "#fc532d"
# bspc config normal_border_color "#353535"
